spring.application.name=GestionSistema
server.port=8087

# MySQL Configuration - LOCAL
#spring.datasource.url=jdbc:mysql://localhost:3306/dbinventory?noAccessToProcedureBodies=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
#spring.datasource.username=root
#spring.datasource.password=admin123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SQL Server Configuration
# conecion de seya
# spring.datasource.SQL.url=jdbc:sqlserver://DESKTOP-HBLC4DM\\MSSQL2022:1433;databaseName=DB_SEYACLOUD_PRINCIPAL;encrypt=true;trustServerCertificate=true;
# spring.datasource.SQL.username=sa
# spring.datasource.SQL.password=admin123
# spring.datasource.SQL.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# conecion de david
spring.datasource.SQL.url=jdbc:sqlserver://192.168.101.71:1433;databaseName=DB_SEYACLOUD_PRINCIPAL;encrypt=true;trustServerCertificate=true;
spring.datasource.SQL.username=sa
spring.datasource.SQL.password=sf-25
spring.datasource.SQL.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===================================================================================
# OCULTAR SCHEMAS EN EL SWAGGER
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.doc-expansion=none
# ===================================================================================

# ===================================================================================
# JWT Configuration
jwt.secret=SeyaCloudSecretKeyGestionGeneralAndValidacionInteraccionesModulosSistema
jwt.expiration=86400000
# ===================================================================================

# ===================================================================================
# Encriptacion Password
app.security.password-seed=miSemillaSegura2024
encriptacion.password.min-length=8
encriptacion.password.require-uppercase=true
encriptacion.password.require-lowercase=true
encriptacion.password.require-numbers=true
# ===================================================================================

# ===================================================================================
# Configuracion REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
# ===================================================================================

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
