package com.SeyaCloudGestion.GestionSistema.feacture.contactosClientes.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.contactosClientes.application.dto.request.RequestRegistroContactoCliente;
import com.SeyaCloudGestion.GestionSistema.feacture.contactosClientes.application.dto.response.ResponseRegistroContactoCliente;

public interface IContactoClienteRegistro {
    ResponseRegistroContactoCliente RegistroContactoCliente(RequestRegistroContactoCliente request);
}