package com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.application.dto.request.RequestRegistroMovimientoStock;
import com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.application.dto.response.ResponseRegistroMovimientoStock;

public interface IMovimientoStockRegistro {
    ResponseRegistroMovimientoStock RegistroMovimientoStock(RequestRegistroMovimientoStock request);
}