package com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.application.dto.request.RequestEditarAllMovimientoStock;
import com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.application.dto.request.RequestEditarEstadoMovimientoStock;
import com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.application.dto.response.ResponseEditarAllMovimientoStock;
import com.SeyaCloudGestion.GestionSistema.feacture.movimientosStock.application.dto.response.ResponseEditarEstadoMovimientoStock;

public interface IMovimientoStockEdicion {
    ResponseEditarAllMovimientoStock EditarAllMovimientoStock(RequestEditarAllMovimientoStock request);
    ResponseEditarEstadoMovimientoStock EditarEstadoMovimientoStock(RequestEditarEstadoMovimientoStock request, int estado);
}