package com.SeyaCloudGestion.GestionSistema.feacture.tipoPromociones.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.tipoPromociones.application.dto.request.RequestEditarAllTipoPromociones;
import com.SeyaCloudGestion.GestionSistema.feacture.tipoPromociones.application.dto.request.RequestEditarEstadoTipoPromociones;
import com.SeyaCloudGestion.GestionSistema.feacture.tipoPromociones.application.dto.response.ResponseEditarAllTipoPromociones;
import com.SeyaCloudGestion.GestionSistema.feacture.tipoPromociones.application.dto.response.ResponseEditarEstadoTipoPromociones;

public interface ITipoPromocionesEdicion {
    ResponseEditarAllTipoPromociones EditarAllTipoPromociones(RequestEditarAllTipoPromociones request);
    ResponseEditarEstadoTipoPromociones EditarEstadoTipoPromociones(RequestEditarEstadoTipoPromociones request, int estado);
}