package com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.application.dto.request.RequestRegistroDetalleTransferencia;
import com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.application.dto.response.ResponseRegistroTransferenciaDetalle;

public interface ITransferenciaDetalleRegistro {
    ResponseRegistroTransferenciaDetalle RegistroDetalleTransferencia(long idTransferencia, RequestRegistroDetalleTransferencia request,double costoUnitario);
}
