package com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.application.dto.request.RequestListaDetalleTransferencia;
import com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.application.dto.response.ResponseListaTransferenciaDetalle;

public interface ITransferenciaDetalleListado {
    public ResponseListaTransferenciaDetalle listaDetalleTransferencia(RequestListaDetalleTransferencia request);
}