package com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.application.dto.request.RequestListaTransferenciaDetalle;
import com.SeyaCloudGestion.GestionSistema.feacture.transferenciaDetalles.application.dto.response.ResponseListaTransferenciaDetalle;

public interface ITransferenciaDetalleListado {
    ResponseListaTransferenciaDetalle listaTransferenciaDetalle(RequestListaTransferenciaDetalle request);
}