package com.SeyaCloudGestion.GestionSistema.feacture.direccionesClientes.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.direccionesClientes.application.dto.request.RequestListaDireccionesClientes;
import com.SeyaCloudGestion.GestionSistema.feacture.direccionesClientes.application.dto.response.ResponseListaDireccionesClientes;

public interface IDireccionesClientesListado {
    ResponseListaDireccionesClientes ListaDireccionesClientes(RequestListaDireccionesClientes request);
}