package com.SeyaCloudGestion.GestionSistema.feacture.cuentasPorCobrar.domain.interfaces;

import com.SeyaCloudGestion.GestionSistema.feacture.cuentasPorCobrar.application.dto.request.RequestAbonarCuentaPorCobrar;
import com.SeyaCloudGestion.GestionSistema.feacture.cuentasPorCobrar.application.dto.request.RequestAnularCuentaPorCobrar;
import com.SeyaCloudGestion.GestionSistema.feacture.cuentasPorCobrar.application.dto.response.ResponseAbonarCuentaPorCobrar;
import com.SeyaCloudGestion.GestionSistema.feacture.cuentasPorCobrar.application.dto.response.ResponseAnularCuentaPorCobrar;
import com.SeyaCloudGestion.GestionSistema.feacture.cuentasPorCobrar.infraestructure.persistence.model.EstadoCuenta;

public interface ICuentasPorCobrarEdicion {
    ResponseAbonarCuentaPorCobrar AbonarCuentasPorCobrar(RequestAbonarCuentaPorCobrar request, EstadoCuenta estado,double monteoPendienteActual);
}